name: Display System Environment Variables

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  display-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Display System Environment Variables
      run: |
        echo "\t -- ALL GITHUB ACTION SYSTEM VARIABLES -- "
        echo "GITHUB_TOKEN: $GITHUB_TOKEN"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "RUNNER_OS: $RUNNER_OS"
        echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
        echo "RUNNER_TEMP: $RUNNER_TEMP"
        echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
        echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
        echo "REPO_NAME: ${{ github.event.repository.name }}"
        
